version: '3'

services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env_pg
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    container_name: flask
    build: ./app
    stop_signal: SIGINT
    restart: always
    env_file:
      - .env_flask
    ports:
      - 8000:8000
    # networks:
    #   - backend
    depends_on:
      - db

volumes:
  db_data:

# networks:
#   backend:
#     driver: bridge