version: '3'

services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    env_file:
      - .env_pg
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/

  web:
    container_name: web
    build: ./web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./web:/usr/src/app
    restart: always
    env_file:
      - .env_flask
    ports:
      - "5000:5000"
    # networks:
    #   - backend
    depends_on:
      - db

volumes:
  db_data:

# networks:
#   backend:
#     driver: bridge