version: '3'

services:
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env_pg
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/

  web:
    container_name: flask
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/usr/src/app/static
    env_file:
      - .env_flask
    restart: always
    ports:
      - "5000:5000"
    expose:
      - 5000
    # networks:
    #   - backend
    depends_on:
      - db

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - "1337:80"
    depends_on:
      - web

volumes:
  db_data:
  static_volume:

# networks:
#   backend:
#     driver: bridge